FROM node:22-bullseye

WORKDIR /app

# Copiamos solo package.json y package-lock.json para instalar deps
COPY package*.json ./
RUN npm ci

# NO copiamos el resto del código aquí, lo montaremos con volumes
EXPOSE 8080

CMD ["npm", "run", "dev"]