services:
  app:
    build: 
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules 
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/buddyreads
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=buddyreads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DATABASE_URL=postgres://postgres:password@postgres:5432/buddyreads
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CALLBACK_URL=http://localhost:8080/api/auth/google/callback
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_jwt_key_here}
      - SESSION_SECRET=${SESSION_SECRET:-your_session_secret_here}
      - LOG_LEVEL=info
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_started

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'
      
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=buddyreads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:  
      test: ["CMD-SHELL", "pg_isready -U postgres -d buddyreads"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mongo_data:
  postgres_data: